# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
provider "google" {
  region = "us-central1"
  zone    = "us-central1-c"
  credentials = file("/Users/chaitu/gcp-migration-334418-1496f4dcabbe.json")
  project = "gcp-migration-334418"
 
}
