# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "gcs" {
    bucket = "my-terragrunt-terraform-state-non-prod-us-east-1"
    prefix = "non-prod/us-east-1/Dev-1/instances/terraform.tfstate"
  }
}
